export const ACT_FETCH_AREA_PAGING = 'fetchAllAreas'
export const ACT_FETCH_AREA_PARENT = 'fetchParentAreas'
export const ACT_UPDATE_AREA_STATUS = 'actUpdateAreaStatus'
export const ACT_DELETE_AREA = 'actDeleteArea'
export const ACT_INSERT_AREA = 'actInsertArea'
export const ACT_EDIT_AREA = 'actEditArea'
export const ACT_FETCH_ONE_AREA = 'actFetchOneArea'
export const ACT_FETCH_AREA_ALL = 'fetchAllAreasByParent'
export const ACT_GET_ALL_CHILD_AREA = 'fetchAllChildArea'
export const ACT_UPDATE_THUMB = 'actUpdateThumb'
export const ACT_UPDATE_JSON = 'actUpdateJson'

export const MUTATION_FETCH_ALL = 'mutationFetchAllAreasParent'
export const MUTATION_FETCH_ALL_AREA = 'mutationFetchAllAreas'
export const MUTATION_DELETE_AREA = 'mutationDeleteUser'
export const MUTATION_FETCH_ALL_PARENT_AREA = 'mutationFetchAllParentAreas'
export const MUTATION_GET_ALL_CHILD_AREA = 'mutationGetAllChildArea'
