export const ACT_FETCH_ROBOT_ACTION_PAGING = 'fetchAllRobotActions'
export const ACT_DELETE_ROBOT_ACTION = 'actDeleteRobotAction'
export const ACT_INSERT_ROBOT_ACTION = 'actInsertRobotAction'
export const ACT_INSERT_ROBOT_SCHEDULE = 'actInsertRobotSchedule'
export const ACT_GET_ROBOT_SCHEDULE = 'actGetRobotSchedule'
export const ACT_GET_ACTION_PARRAM = 'actGetActionParram'
export const ACT_UPDATE_ACTION_PARRAM= 'actUpdateActionParram'
export const ACT_UPDATE_ROBOT_ACTION = 'actUpdatetRobotAction'
export const ACT_FETCH_ALL_ROBOT_ACTIONS = 'actFetchAllRobotActions'
export const ACT_FETCH_ONE_ROBOT_ACTION = 'actFetcOneRobotAction'
export const ACT_GET_LIST_MANUAL = 'fetchAllManualActions'

export const MUTATION_FETCH_PAGING_ROBOT_ACTION = 'mutationFetchPagingRobotActions'
export const MUTATION_DELETE_ROBOT_ACTION = 'mutationDeleteRobotAction'
export const MUTATION_GET_ALL_ROBOT_ACTIONS = 'mutationGetAllRobotActions'
export const MUTATION_FETCH_MANUAL_ACTIONS = 'mutationFetchManualActions'
export const MUTATION_FETCH_ROBOT_SCHEDULE = 'mutationFetchRobotSchedule'
