export const ACT_FETCH_USER_PAGING = 'fetchAllUsers'
export const ACT_RESET_PASSWORD = 'actResetPassword'
export const ACT_UPDATE_STATUS = 'actUpdateStatus'
export const ACT_DELETE_USER = 'actDeleteUser'
export const ACT_INSERT_USER = 'actInsertUser'
export const ACT_EDIT_USER = 'actEditUser'
export const ACT_FETCH_ONE_USER = 'actFetchOneUser'
export const ACT_FETCH_ROLES = 'actFetchRoles'

export const MUTATION_FETCH_ALL_USER = 'mutationFetchAllUsers'
export const MUTATION_DELETE_USER = 'mutationDeleteUser'
export const MUTATION_FETCH_ROLES = 'mutationFetchRoles'

export const MUTATION_USER_FETCH_ALL_PARENT_AREA = 'mutationUserFetchAllParentArea'
export const MUTATION_USER_GET_ALL_CHILD_AREA = 'fetchAllChildAreaUser'
export const MUTATION_USER_PARENT_AREA = 'mutationSetUserParentArea'
export const ACT_GET_PARENT_AREA = 'actUserGetParentArea'
export const ACT_GET_CHILD_AREA_BY_PARENT = 'actUserGetChildAreaByParent'
export const ACT_SET_PARENT_AREA = 'actUserSetParentArea'

export const ACT_GET_ROBOT_BY_AREA = 'actGetRobotByArea'
export const ACT_MUTATION_ROBOT_BY_AREA = 'mutationGetRobotByArea'
